### ISSUE TITLE
Explorer Api unavailability brakes script

### ISSUE THREAD

**Issue by jokumo** [inlak16/AMB-NET-TouchBar-Dashboard_and_Node_Tools#1]
I don't get notifications since 2 days. Running the script manually reveales that an exception is drawn on Line 206, where script feches a json from "https://explorer-api.ambrosus-test.io/hermeses". This page seems to be unavailable at the moment. Not sure if the URL changed or if the explorer api of the test net is broken and temporarily down.

I already posted this finding in the telegram group. So maybe it comes back online and everything works as before.

However, one Idea to prevent such a failure in the future could be to catch this exception and send an error message to telegram instead.
I might look into it upcoming week, if I find the time to do so.

**Comment by inlak16** [comment]
Fixed in v3.3 of the Telegram Notification script. All used APIs are checked for Data availability now with the daily status message showing if main APIs are not available. Edge cases are still unexpected API data-structure changes.

**Comment by jokumo** [comment]
Wow, that was fast. Thanks man, your script is very useful.
